version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  commit-message:
    prefix: ci
    include: scope
- package-ecosystem: docker
  directory: "/alpine"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  commit-message:
    prefix: fix
    include: scope
- package-ecosystem: gradle
  directory: "/tests"
  token: ${{ secrets.GH_PACKAGES_TOKEN }}
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  commit-message:
    prefix: chore
    include: scope