version: 1
update_configs:
  - package_manager: "docker"
    directory: "/alpine"
    update_schedule: "daily"
    commit_message:
      prefix: "fix"
      include_scope: true
  - package_manager: "docker"
    directory: "/centos"
    update_schedule: "daily"
    commit_message:
      prefix: "fix"
      include_scope: true
  - package_manager: "github_actions"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "ci"
      include_scope: true