name: CI PR/Branch
on:
  push:
    branches-ignore:
      - master
  pull_request:

env:
  IMAGE_NAME: homecentr/base  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [ "alpine", "centos" ]
    steps:
      - uses: actions/checkout@master
      
      - name: Set tag var
        id: vars
        run: echo ::set-output name=docker_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}

      - name: Verify Dockerfile with Hadolint
        uses: brpaz/hadolint-action@master      
        with:
          dockerfile: "${{ matrix.base }}/Dockerfile"

      - name: Build Docker image
        run: "cd {{ matrix.base }} && docker build . -t ${{ env.IMAGE_NAME }}:${{ matrix.base }}-${{ steps.vars.outputs.docker_tag }}"

      - name: Scan with Phonito Security
        uses: phonito/phonito-scanner-action@master
        with:
          image: ${{ env.IMAGE_NAME }}:${{ matrix.base }}-${{ steps.vars.outputs.docker_tag }}
          phonito-token: '${{ secrets.PHONITO_TOKEN }}'      