name: CI/CD on master
on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: "homecentr/base"

jobs:
  common:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      
      - name: "Determine release version"
        uses: docker://ghcr.io/codfish/semantic-release-action:v1.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Write version to a file"
        shell: bash
        run: |
          echo $RELEASE_VERSION > version.txt

      - name: "Upload version number as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: version
          path: version.txt

      - name: "Update Docker Hub description"
        uses: peter-evans/dockerhub-description@v3.3.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: ${{ env.IMAGE_NAME }}

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - common
    strategy:
      matrix:
        base: [ "alpine" ]
    steps:
      - name: Download version artifact
        uses: actions/download-artifact@v3
        with:
          name: version

      - name: Read version from file into a variable
        run: "echo ::set-env name=RELEASE_VERSION::$(cat version.txt)"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - uses: actions/checkout@master

      - name: Verify Dockerfile with Hadolint
        if: env.RELEASE_VERSION != ''
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "${{ matrix.base }}/Dockerfile"

      - name: "Build Docker image"
        if: env.RELEASE_VERSION != ''
        run: |
          cd ${{ matrix.base }} && docker build . \
              --tag "$IMAGE_NAME:$RELEASE_VERSION-${{ matrix.base }}" \
              --tag "$IMAGE_NAME:latest-${{ matrix.base }}" \
              --tag "ghcr.io/$IMAGE_NAME:$RELEASE_VERSION-${{ matrix.base }}" \
              --tag "ghcr.io/$IMAGE_NAME:latest-${{ matrix.base }}" \
              --label "org.label-schema.schema-version=1.0" \
              --label "org.label-schema.vcs-ref=${GITHUB_SHA}" \
              --label "org.label-schema.vcs-url=https://github.com/${GITHUB_REPOSITORY}" \
              --label "org.label-schema.url=https://github.com/${GITHUB_REPOSITORY}" \
              --label "org.label-schema.vendor=HomeCentr" \
              --label "version=$RELEASE_VERSION-${{ matrix.base }}" \
              --label "org.label-schema.build-date=$(date '+%F %T')"

      - name: Test Docker image
        if: env.RELEASE_VERSION != ''
        run: |
          chmod 777 ${{ matrix.base }}/example
          chmod a+x ${{ matrix.base }}/example/*
          cd tests
          gradle test -Ddocker_image_tag=${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}-${{ matrix.base }} -Dbase=${{ matrix.base }}
        env: # To allow downloading packages
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Docker Hub
      - name: "Log into Docker Hub"
        if: env.RELEASE_VERSION != ''
        run: "echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin"

      - name: "Push images to Docker Hub"
        if: env.RELEASE_VERSION != ''
        run: "docker push $IMAGE_NAME:$RELEASE_VERSION-${{ matrix.base }} && docker push $IMAGE_NAME:latest-${{ matrix.base }}"

      # GitHub
      - name: "Log into GitHub Packages"
        if: env.RELEASE_VERSION != ''
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: "Push to GitHub Packages"
        if: env.RELEASE_VERSION != ''
        run: "docker push ghcr.io/$IMAGE_NAME:$RELEASE_VERSION-${{ matrix.base }} && docker push ghcr.io/$IMAGE_NAME:latest-${{ matrix.base }}"