name: CI/CD on master
on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: "homecentr/base"

jobs:
  common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: "Determine release version"
        uses: codfish/semantic-release-action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_URL: "https://api.github.com"

      - name: "Write version to a file"
        shell: bash
        run: |
          echo $RELEASE_VERSION > version.txt

      - name: "Upload version number as artifact"
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt

      - name: "Update Docker Hub description"
        uses: peter-evans/dockerhub-description@v2.4.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: ${{ env.IMAGE_NAME }}

  build:
    runs-on: ubuntu-latest
    needs:
      - common
    strategy:
      matrix:
        base: [ "alpine" ]
    steps:
      - name: Download version artifact
        uses: actions/download-artifact@v2
        with:
          name: version

      - name: Read version into a variable
        run: "echo ::set-env name=RELEASE_VERSION::$(cat version/version.txt)"

      - uses: actions/checkout@master

      - name: Verify Dockerfile with Hadolint
        if: env.RELEASE_VERSION != ''
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "${{ matrix.base }}/Dockerfile"

      - name: "Build Docker image"
        if: env.RELEASE_VERSION != ''
        run: |
          cd ${{ matrix.base }} && docker build . -t "$IMAGE_NAME:$RELEASE_VERSION-${{ matrix.base }}" \
              --label "org.label-schema.schema-version=1.0" \
              --label "org.label-schema.vcs-ref=${GITHUB_SHA}" \
              --label "org.label-schema.vcs-url=https://github.com/${GITHUB_REPOSITORY}" \
              --label "org.label-schema.url=https://github.com/${GITHUB_REPOSITORY}" \
              --label "org.label-schema.vendor=HomeCentr" \
              --label "version=$RELEASE_VERSION-${{ matrix.base }}" \
              --label "org.label-schema.build-date=$(date '+%F %T')"

      - name: Scan with Phonito Security
        if: env.RELEASE_VERSION != ''
        uses: phonito/phonito-scanner-action@master
        with:
          image: ${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}-${{ matrix.base }}
          phonito-token: '${{ secrets.PHONITO_TOKEN }}'

      - name: Scan with Snyk
        if: env.RELEASE_VERSION != ''
        uses: snyk/actions/docker@0.1.1
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}-${{ matrix.base }}

      - name: Test Docker image
        if: env.RELEASE_VERSION != ''
        run: |
          chmod 777 ${{ matrix.base }}/example
          chmod a+x ${{ matrix.base }}/example/*
          cd tests
          gradle test -Ddocker_image_tag=${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}-${{ matrix.base }} -Dbase=${{ matrix.base }}

      - name: "Tag image as latest"
        if: env.RELEASE_VERSION != ''
        run: "docker tag $IMAGE_NAME:$RELEASE_VERSION-${{ matrix.base }} $IMAGE_NAME:latest-${{ matrix.base }}"

      - name: "Log into Docker Hub"
        if: env.RELEASE_VERSION != ''
        run: "echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin"

      - name: "Push versioned image"
        if: env.RELEASE_VERSION != ''
        run: "docker push $IMAGE_NAME:$RELEASE_VERSION-${{ matrix.base }}"

      - name: "Push latest image"
        if: env.RELEASE_VERSION != ''
        run: "docker push $IMAGE_NAME:latest-${{ matrix.base }}"
