name: Regular Docker image vulnerability scan
on:
  schedule:
    - cron: '0 6 * * *'

env:
  IMAGE_NAME: "homecentr/base"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [ "alpine", "centos" ]
    steps:
      - name: Pull Docker image
        run: docker pull ${{ env.IMAGE_NAME }}:latest-${{ matrix.base }}

      - name: Scan image for vulnerabilities
        uses: phonito/phonito-scanner-action@master
        with:
          image: ${{ env.IMAGE_NAME }}:latest-${{ matrix.base }}
          phonito-token: '${{ secrets.PHONITO_TOKEN }}'